# Arrests analysis

## Importing libraries

In [15]:
import pandas as pd
import numpy as np
import os

from matplotlib import pyplot
%matplotlib inline

## Importing database

In [5]:
crimes = pd.read_csv("/Users/oleoaraujo/Desktop/Crimes-in-Chicago/Crimes_-_2015_to_2020.csv")

In [7]:
crimes.head(20)

,ID,Case Number,Date,Block,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,Year,Updated On,Latitude,Longitude,Location
0,10224738,HY411648,2015-09-05 13:30:00,043XX S WOOD ST,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,924,9.0,12.0,61.0,2015,2018-02-10 15:50:01,41.815117,-87.670000,"(41.815117282, -87.669999562)"
1,10224739,HY411615,2015-09-04 11:30:00,008XX N CENTRAL AVE,THEFT,POCKET-PICKING,CTA BUS,False,False,1511,15.0,29.0,25.0,2015,2018-02-10 15:50:01,41.895080,-87.765400,"(41.895080471, -87.765400451)"
2,11646166,JC213529,2018-09-01 00:01:00,082XX S INGLESIDE AVE,THEFT,OVER $500,RESIDENCE,False,True,631,6.0,8.0,44.0,2018,2019-04-06 16:04:43,NaN,NaN,NaN
3,10224740,HY411595,2015-09-05 12:45:00,035XX W BARRY AVE,NARCOTICS,POSS: HEROIN(BRN/TAN),SIDEWALK,True,False,1412,14.0,35.0,21.0,2015,2018-02-10 15:50:01,41.937406,-87.716650,"(41.937405765, -87.716649687)"
4,10224741,HY411610,2015-09-05 13:00:00,0000X N LARAMIE AVE,ASSAULT,SIMPLE,APARTMENT,False,True,1522,15.0,28.0,25.0,2015,2018-02-10 15:50:01,41.881903,-87.755121,"(41.881903443, -87.755121152)"
5,10224742,HY411435,2015-09-05 10:55:00,082XX S LOOMIS BLVD,BURGLARY,FORCIBLE ENTRY,RESIDENCE,False,False,614,6.0,21.0,71.0,2015,2018-02-10 15:50:01,41.744379,-87.658431,"(41.744378879, -87.658430635)"
6,10224743,HY411629,2015-09-04 18:00:00,021XX W CHURCHILL ST,BURGLARY,UNLAWFUL ENTRY,RESIDENCE-GARAGE,False,False,1434,14.0,32.0,24.0,2015,2018-02-10 15:50:01,41.914636,-87.681631,"(41.914635603, -87.681630909)"
7,10224744,HY411605,2015-09-05 13:00:00,025XX W CERMAK RD,THEFT,RETAIL THEFT,GROCERY FOOD STORE,True,False,1034,10.0,25.0,31.0,2015,2015-09-17 11:37:18,41.851989,-87.689219,"(41.851988885, -87.689219118)"
8,10224745,HY411654,2015-09-05 11:30:00,031XX W WASHINGTON BLVD,ROBBERY,STRONGARM - NO WEAPON,STREET,False,True,1222,12.0,27.0,27.0,2015,2018-02-10 15:50:01,41.882814,-87.704326,"(41.88281374, -87.704325717)"
9,11645836,JC212333,2016-05-01 00:25:00,055XX S ROCKWELL ST,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,824,8.0,15.0,63.0,2016,2019-04-06 16:04:43,NaN,NaN,NaN
10,10224746,HY411662,2015-09-05 14:00:00,071XX S PULASKI RD,THEFT,$500 AND UNDER,PARKING LOT/GARAGE(NON.RESID.),False,False,833,8.0,13.0,65.0,2015,2018-02-10 15:50:01,41.763648,-87.722345,"(41.763647552, -87.722344693)"
11,10224749,HY411626,2015-09-05 11:00:00,052XX N MILWAUKEE AVE,BATTERY,SIMPLE,SMALL RETAIL STORE,False,False,1623,16.0,45.0,11.0,2015,2018-02-10 15:50:01,41.975968,-87.768014,"(41.975968415, -87.768014257)"
12,10224750,HY411632,2015-09-05 03:00:00,0000X W 103RD ST,OTHER OFFENSE,TELEPHONE THREAT,APARTMENT,False,True,512,5.0,34.0,49.0,2015,2018-02-10 15:50:01,41.707155,-87.624245,"(41.707154919, -87.624244993)"
13,10224751,HY411566,2015-09-05 12:50:00,013XX E 47TH ST,BATTERY,DOMESTIC BATTERY SIMPLE,STREET,False,True,222,2.0,4.0,39.0,2015,2018-02-10 15:50:01,41.809678,-87.593639,"(41.809678314, -87.593638934)"
14,10224752,HY411601,2015-09-03 13:00:00,020XX W SCHILLER ST,THEFT,OVER $500,STREET,False,False,1424,14.0,1.0,24.0,2015,2018-02-10 15:50:01,41.907127,-87.678232,"(41.907127255, -87.678232016)"
15,10224753,HY411489,2015-09-05 11:45:00,080XX S JUSTINE ST,BATTERY,AGGRAVATED DOMESTIC BATTERY: OTHER DANG WEAPON,APARTMENT,False,False,612,6.0,21.0,71.0,2015,2018-02-10 15:50:01,41.748097,-87.662166,"(41.748097343, -87.662166183)"
16,10224754,HY411656,2015-09-05 13:30:00,007XX N LEAMINGTON AVE,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,1531,15.0,28.0,25.0,2015,2018-02-10 15:50:01,41.893870,-87.754341,"(41.893869916, -87.754341096)"
17,10224756,HY410094,2015-07-08 00:00:00,103XX S TORRENCE AVE,BURGLARY,UNLAWFUL ENTRY,OTHER,False,False,434,4.0,10.0,51.0,2015,2018-02-10 15:50:01,41.707490,-87.559650,"(41.707490122, -87.559650325)"
18,10224757,HY411388,2015-09-05 09:55:00,088XX S PAULINA ST,BURGLARY,FORCIBLE ENTRY,RESIDENCE,True,False,2221,22.0,21.0,71.0,2015,2018-02-10 15:50:01,41.733174,-87.665421,"(41.733173536, -87.665421067)"
19,10224758,HY411568,2015-09-05 12:35:00,059XX W GRACE ST,BATTERY,DOMESTIC BATTERY SIMPLE,STREET,False,True,1633,16.0,38.0,15.0,2015,2018-02-10 15:50:01,41.949430,-87.775436,"(41.949429769, -87.775435529)"

In [8]:
crimes.set_index(crimes.ID, inplace=True)

In [9]:
crimes.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
ID,1541733.0,NaN,NaN,NaN,11102325.804722,860134.560531,21714.0,10571765.0,11156741.0,11687324.0,12305810.0
Case Number,1541733,1541546,HZ140230,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Date,1541733,702137,2015-01-01 00:01:00,187,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Block,1541733,35135,001XX N STATE ST,5094,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Primary Type,1541733,35,THEFT,352089,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Description,1541733,492,SIMPLE,168057,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Location Description,1535379,192,STREET,347634,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arrest,1541733,2,False,1223135,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Domestic,1541733,2,False,1287168,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Beat,1541733.0,NaN,NaN,NaN,1143.751639,694.631456,111.0,612.0,1024.0,1712.0,2535.0
District,1541732.0,NaN,NaN,NaN,11.208901,6.939356,1.0,6.0,10.0,17.0,31.0
Ward,1541702.0,NaN,NaN,NaN,23.152654,13.9437,1.0,10.0,24.0,34.0,50.0
Community Area,1541732.0,NaN,NaN,NaN,36.914989,21.432076,1.0,23.0,32.0,54.0,77.0
Year,1541733.0,NaN,NaN,NaN,2017.402891,1.665876,2015.0,2016.0,2017.0,2019.0,2020.0
Updated On,1541733,3539,2018-02-10 15:50:01,729832,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Latitude,1521192.0,NaN,NaN,NaN,41.843167,0.086222,36.619446,41.768287,41.862363,41.90495,42.022671
Longitude,1521192.0,NaN,NaN,NaN,-87.670788,0.059251,-91.686566,-87.713599,-87.664343,-87.627845,-87.524529
Location,1521192,368492,"(41.883500187, -87.627876698)",2738,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
crimes.dtypes

ID                        int64
Case Number              object
Date                     object
Block                    object
Primary Type             object
Description              object
Location Description     object
Arrest                     bool
Domestic                   bool
Beat                      int64
District                float64
Ward                    float64
Community Area          float64
Year                      int64
Updated On               object
Latitude                float64
Longitude               float64
Location                 object
dtype: object

In [12]:
# Define "Date" and "Updated on" columns as datetime type
crimes.Date = pd.to_datetime(crimes.Date)
crimes["Updated On"] = pd.to_datetime(crimes["Updated On"])

crimes.dtypes

ID                               int64
Case Number                     object
Date                    datetime64[ns]
Block                           object
Primary Type                    object
Description                     object
Location Description            object
Arrest                            bool
Domestic                          bool
Beat                             int64
District                       float64
Ward                           float64
Community Area                 float64
Year                             int64
Updated On              datetime64[ns]
Latitude                       float64
Longitude                      float64
Location                        object
dtype: object

## Arrests

In [25]:
crimes.Arrest.describe()

count     1541733
unique          2
top         False
freq      1223135
Name: Arrest, dtype: object